# Generated by Django 3.0.4 on 2020-04-15 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airtrans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardingPass',
            fields=[
                ('ticket_no_and_flight_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='airtrans.TicketFlight')),
                ('boarding_no', models.IntegerField()),
                ('seat_no', models.CharField(max_length=10)),
            ],
        ),
    ]
