# Generated by Django 3.0.3 on 2020-10-28 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0003_auto_20201023_2019'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, unique=True)),
                ('type', models.CharField(choices=[('1', 'fruct'), ('2', 'veg'), (None, 'Unknown')], max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Shop.Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shop.User')),
            ],
            options={
                'unique_together': {('user', 'product')},

            },
        ),
    ]
