# Generated by Django 3.0.3 on 2020-11-02 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0005_auto_20201102_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(blank=True, choices=[('1', 'fruit'), ('2', 'veg'), (None, 'Unknown')], max_length=20, null=True),
        ),
    ]
